name: layrz_protocol
description: Layrz Link Protocol
version: "2.7.5"
repository: https://github.com/goldenm-software/layrz_protocol_dart

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  layrz_models: ^3.4.6
  layrz_logging: ^1.1.0
  layrz_theme: ^7.3.1
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
