#!/usr/bin/env python3
"""
Generate canonical Pb and Pm wire frames and write them as C++ string literals
into tests/fixtures/canonical_frames_generated.hpp.

Run from the repo root or from cpp/:
    python3 scripts/gen_pb_pm_fixtures.py

Requires the layrz_protocol Python package (uv run in python/):
    cd python && uv run python ../cpp/scripts/gen_pb_pm_fixtures.py
"""
import sys
import os
import datetime

# Resolve the Python package path
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, os.path.join(repo_root, 'python'))

from layrz_protocol.packets.client.pb import PbPacket
from layrz_protocol.packets.client.pm import PmPacket
from layrz_protocol.packets.definitions.ble_advertisement import BleAdvertisement
from layrz_protocol.packets.definitions.ble_manufacturer_data import BleManufacturerData
from layrz_protocol.packets.definitions.ble_service_data import BleServiceData
from layrz_protocol.constants import UTC

FIXED_TS = datetime.datetime(2023, 11, 14, 22, 13, 20, tzinfo=UTC)  # 1700000000 Unix

# ── Pb fixture ────────────────────────────────────────────────────────────────
mfr = BleManufacturerData(company_id=0x004C, data=[0xAA, 0xBB, 0xCC])
svc = BleServiceData(uuid=0xFD6F, data=[0x01, 0x02])

adv1 = BleAdvertisement(
    mac_address='12:34:56:78:90:AB',
    timestamp=FIXED_TS,
    latitude=10.0,
    longitude=20.0,
    altitude=100.0,
    model='GENERIC',
    device_name='TestDevice',
    rssi=-70,
    tx_power=None,
    manufacturer_data=[mfr],
    service_data=[svc],
)

adv2 = BleAdvertisement(
    mac_address='BC:09:87:65:43:21',
    timestamp=FIXED_TS,
    latitude=None,
    longitude=None,
    altitude=None,
    model='GENERIC',
    device_name='',
    rssi=-80,
    tx_power=-10,
    manufacturer_data=[],
    service_data=[],
)

pb_pkt = PbPacket(advertisements=[adv1, adv2])
pb_frame = pb_pkt.to_packet()
print(f"Pb frame: {pb_frame}")

# ── Pm fixture ────────────────────────────────────────────────────────────────
pm_pkt = PmPacket(
    filename='test.jpg',
    content_type='image/jpeg',
    data=bytes([0xFF, 0xD8, 0xFF, 0xE0]),  # minimal JPEG header
)
pm_frame = pm_pkt.to_packet()
print(f"Pm frame: {pm_frame}")

# ── Write C++ header ──────────────────────────────────────────────────────────
out_path = os.path.join(os.path.dirname(__file__), '..', 'tests', 'fixtures',
                        'canonical_frames_generated.hpp')

header = f'''\
#pragma once
// AUTO-GENERATED by scripts/gen_pb_pm_fixtures.py — do not edit by hand.
// Re-generate with: cd python && uv run python ../cpp/scripts/gen_pb_pm_fixtures.py

#include <string>

namespace layrz::protocol::fixtures {{

// Pb: two advertisements (adv1 has MFR+SVC data, adv2 is minimal)
static const std::string FRAME_PB = "{pb_frame}";

// Pm: filename=test.jpg, content_type=image/jpeg, data=FF D8 FF E0
static const std::string FRAME_PM = "{pm_frame}";

}} // namespace layrz::protocol::fixtures
'''

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w') as f:
    f.write(header)

print(f"Written to {out_path}")
