package layrzprotocol

import (
	"testing"
	"time"
)

// Canonical frames generated by the Python reference implementation (source of truth).
// timestamp = 1700000000, uuid = "12345678-1234-5678-1234-567812345678"
var canonicalFrames = map[string]string{
	"Ao": "<Ao>1700000000;A058</Ao>",
	"Ar": "<Ar>Unknown reason;1DFD</Ar>",
	"As": "<As>;7F28</As>",
	"Au": "<Au>;7F28</Au>",
	"Pa": "<Pa>123456789012345;mypassword;2B64</Pa>",
	"Pc": "<Pc>1700000000;42;ok;A497</Pc>",
	"Pr": "<Pr>;7F28</Pr>",
	"Ts": "<Ts>1700000000;12345678-1234-5678-1234-567812345678;5DA1</Ts>",
	"Te": "<Te>1700000000;12345678-1234-5678-1234-567812345678;1234.567;89.012;3600;7F64</Te>",
	"Im": "<Im>1700000000;12345678-1234-5678-1234-567812345678;Hello||| world;2913</Im>",
}

var (
	fixedTime = time.Unix(1700000000, 0)
	fixedUUID = "12345678-1234-5678-1234-567812345678"
)

// copy returns a mutable copy so FromPacket's in-place mutation doesn't clobber the canonical.
func copy(s string) string { return s + "" }

func TestRoundTrip_Ao(t *testing.T) {
	canonical := canonicalFrames["Ao"]
	raw := copy(canonical)

	p := AoPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Timestamp.Unix() != fixedTime.Unix() {
		t.Errorf("timestamp mismatch: got %v, want %v", p.Timestamp.Unix(), fixedTime.Unix())
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Ar(t *testing.T) {
	canonical := canonicalFrames["Ar"]
	raw := copy(canonical)

	p := ArPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Reason != "Unknown reason" {
		t.Errorf("reason mismatch: got %q, want %q", p.Reason, "Unknown reason")
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_As(t *testing.T) {
	canonical := canonicalFrames["As"]
	raw := copy(canonical)

	p := AsPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Au(t *testing.T) {
	canonical := canonicalFrames["Au"]
	raw := copy(canonical)

	p := AuPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Pa(t *testing.T) {
	canonical := canonicalFrames["Pa"]
	raw := copy(canonical)

	p := PaPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if *p.Ident != "123456789012345" {
		t.Errorf("ident mismatch: got %q", *p.Ident)
	}
	if *p.Password != "mypassword" {
		t.Errorf("password mismatch: got %q", *p.Password)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Pc(t *testing.T) {
	canonical := canonicalFrames["Pc"]
	raw := copy(canonical)

	p := PcPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Timestamp.Unix() != fixedTime.Unix() {
		t.Errorf("timestamp mismatch: got %v, want %v", p.Timestamp.Unix(), fixedTime.Unix())
	}
	if p.CommandId != 42 {
		t.Errorf("command_id mismatch: got %d, want 42", p.CommandId)
	}
	if *p.Message != "ok" {
		t.Errorf("message mismatch: got %q", *p.Message)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Pr(t *testing.T) {
	canonical := canonicalFrames["Pr"]
	raw := copy(canonical)

	p := PrPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Ts(t *testing.T) {
	canonical := canonicalFrames["Ts"]
	raw := copy(canonical)

	p := TsPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Timestamp.Unix() != fixedTime.Unix() {
		t.Errorf("timestamp mismatch: got %v, want %v", p.Timestamp.Unix(), fixedTime.Unix())
	}
	if p.TripId != fixedUUID {
		t.Errorf("trip_id mismatch: got %q, want %q", p.TripId, fixedUUID)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Te(t *testing.T) {
	canonical := canonicalFrames["Te"]
	raw := copy(canonical)

	p := TePacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Timestamp.Unix() != fixedTime.Unix() {
		t.Errorf("timestamp mismatch: got %v, want %v", p.Timestamp.Unix(), fixedTime.Unix())
	}
	if p.TripId != fixedUUID {
		t.Errorf("trip_id mismatch: got %q, want %q", p.TripId, fixedUUID)
	}
	if p.DistanceTraveled != 1234.567 {
		t.Errorf("distance_traveled mismatch: got %v, want 1234.567", p.DistanceTraveled)
	}
	if p.MaxSpeed != 89.012 {
		t.Errorf("max_speed mismatch: got %v, want 89.012", p.MaxSpeed)
	}
	if p.Duration.Seconds() != 3600 {
		t.Errorf("duration mismatch: got %v, want 3600s", p.Duration)
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}

func TestRoundTrip_Im(t *testing.T) {
	canonical := canonicalFrames["Im"]
	raw := copy(canonical)

	p := ImPacket{}
	if err := p.FromPacket(&raw); err != nil {
		t.Fatalf("FromPacket failed: %v", err)
	}
	if p.Timestamp.Unix() != fixedTime.Unix() {
		t.Errorf("timestamp mismatch: got %v, want %v", p.Timestamp.Unix(), fixedTime.Unix())
	}
	if p.ChatId != fixedUUID {
		t.Errorf("chat_id mismatch: got %q, want %q", p.ChatId, fixedUUID)
	}
	if p.Message != "Hello; world" {
		t.Errorf("message mismatch: got %q, want %q", p.Message, "Hello; world")
	}

	got := *p.ToPacket()
	if got != canonical {
		t.Errorf("re-encoded mismatch:\n  got  %s\n  want %s", got, canonical)
	}
}
