#pragma once
// AUTO-GENERATED by scripts/gen_pb_pm_fixtures.py — do not edit by hand.
// Re-generate with: cd python && uv run python ../cpp/scripts/gen_pb_pm_fixtures.py

#include <string>

namespace layrz::protocol::fixtures {

// Pb: two advertisements (adv1 has MFR+SVC data, adv2 is minimal)
static const std::string FRAME_PB = "<Pb>1234567890AB;1700000000;10.0;20.0;100.0;GENERIC;TestDevice;-70;;004C:AABBCC;FD6F:0102;C73D;BC0987654321;1700000000;;;;GENERIC;;-80;-10;;;EA51;7032</Pb>";

// Pm: filename=test.jpg, content_type=image/jpeg, data=FF D8 FF E0
static const std::string FRAME_PM = "<Pm>test.jpg;image/jpeg;/9j/4A==;77EC</Pm>";

} // namespace layrz::protocol::fixtures
