#pragma once
// Canonical wire frames — source of truth from Go roundtrip_test.go
// and Python tests/test_1_client_packets.py + test_2_server_packets.py.
//
// Pb and Pm frames are generated by scripts/gen_pb_pm_fixtures.py.
//
// All timestamps use 1700000000 (Unix); UUID = "12345678-1234-5678-1234-567812345678".

#include <string>

namespace layrz::protocol::fixtures {

// ── From Go roundtrip_test.go ──────────────────────────────────────────────
static const std::string FRAME_AO   = "<Ao>1700000000;A058</Ao>";
static const std::string FRAME_AR   = "<Ar>Unknown reason;1DFD</Ar>";
static const std::string FRAME_AS   = "<As>;7F28</As>";
static const std::string FRAME_AU   = "<Au>;7F28</Au>";
static const std::string FRAME_PA   = "<Pa>123456789012345;mypassword;2B64</Pa>";
static const std::string FRAME_PC   = "<Pc>1700000000;42;ok;A497</Pc>";
static const std::string FRAME_PR   = "<Pr>;7F28</Pr>";
static const std::string FRAME_TS   = "<Ts>1700000000;12345678-1234-5678-1234-567812345678;5DA1</Ts>";
static const std::string FRAME_TE   = "<Te>1700000000;12345678-1234-5678-1234-567812345678;1234.567;89.012;3600;7F64</Te>";
static const std::string FRAME_IM   = "<Im>1700000000;12345678-1234-5678-1234-567812345678;Hello||| world;2913</Im>";

// ── From Python test_2_server_packets.py ──────────────────────────────────
// Ab: two devices (MACs 12:34:56:78:90:AB and BC:09:87:65:43:21, model=GENERIC)
static const std::string FRAME_AB   = "<Ab>1234567890AB:GENERIC;BC0987654321:GENERIC;C1BE</Ab>";

// ── From Python test_1_client_packets.py ──────────────────────────────────
// Pd: ts=0, lat/lon/alt/spd/dir=10.0, sat=5, hdop=1.0, extras={...}
static const std::string FRAME_PD   =
    "<Pd>0;10.0;10.0;10.0;10.0;10.0;5;1.0;"
    "test.str:Hola mundo,test.int:1,test.double:1.0,test.bool:true;";
// Note: CRC is appended by the test itself using compute_crc_str
// (the Python test computes the CRC dynamically too)

// Pi: ts=testident, fw=1,1,1,1,1, branch=DEVELOPMENT(1), fota=1
static const std::string FRAME_PI   = "<Pi>testident;1;1;1;1;1;1;1;";

// Ps: ts=0, params={net_wifi_ssid:AWESOME WIFI, ...}
static const std::string FRAME_PS   =
    "<Ps>0;net_wifi_ssid:AWESOME WIFI,net_wifi_pass:dictadormarico69,"
    "net_wifi_sec:WPA2,static.lat:-15.5,static.lng:15.5;";

// Pb/Pm canonical frames are in canonical_frames_generated.hpp (generated by script)

} // namespace layrz::protocol::fixtures
